services:
- type: web
  name: nocodb-iroh
  env: docker
  region: frankfurt # optional (defaults to oregon)
  plan: free # optional (defaults to starter)
  branch: main # optional (defaults to master)
  autoDeploy: true
  healthCheckPath: /dashboard
  envVars:
  - key: DATABASE_URL
    value: YOUR_FULL_DB_URL_WITH_CREDENTIALS
  - key: PORT
    value: 8080
